Update release info to v5.0.0-alpha.0
camunda/camunda-modeler pull request #2705
Opened 2022-01-24 16:23 UTC by barmac

Closes #2670

2022-01-24 19:59 UTC, MaxTru requested changes
Currently this basically includes:

```
1. Cloud 1.4 support
2. New Prop Panel
3. New Data View / Linting errors (wrapped inside information panel, but notice that linting is not new (see forms?))
```

But in fact we have so much in this release. Maybe lets think about having a structure like this:

```
1. Cloud 1.4 support
===> Called Decision
2. Improved overall UI to become a "Visual IDE"
===> Improved Properties Panel, Welcome Page, Tab Bar, and Status Bar
3. Process Debugging for BPMN
===> For Camunda Cloud, the Modeler will now validate and show if BPMN elements are not supported in the target platform
4. Support for Collapsed Sub-Processes
```

Maybe it makes sense to do a short sync meeting to align on the general concept?

2022-01-24 19:59 UTC, MaxTru commented on client/src/plugins/version-info/ReleaseInfo.js
> +          Learn more about this feature in the <a href="https://docs.camunda.io/docs/components/modeler/bpmn/business-rule-tasks/business-rule-tasks/">Camunda Cloud docs on Business Rule Task.</a>
```suggestion
          Learn more about this feature in the <a href="https://docs.camunda.io/docs/components/modeler/bpmn/business-rule-tasks/business-rule-tasks/">Camunda Cloud docs on Business Rule Tasks.</a>
```

...cause the docs have as heading also `Business rule tasks`

2022-01-24 19:59 UTC, MaxTru commented on client/src/plugins/version-info/ReleaseInfo.js
> +          Specify called decision by ID and assign the result to a variable via the properties panel.
Hmmm. Maybe a bit clearer: 

```suggestion
          You can now evaluate a DMN decision in a Business Rules Task.
          Specify the called decision (DMN) by its ID and assign the result to a variable via the properties panel.
```

WDYT?

2022-01-25 08:10 UTC, barmac commented
I think your suggestions make sense. Indeed there's so much in this release.

> 4. Support for Collapsed Sub-Processes
This is not included in this release, but will come later.

2022-01-25 08:17 UTC, andreasgeier commented
> Maybe it makes sense to do a short sync meeting to align on the general concept?

I would suggest that @barmac creates a proposal with the three topics that @MaxTru mentioned: cloud 1.3, Visual IDE (see blog post for inspiration), debugging. Then we can discuss/review.

wdyt?

2022-01-25 11:41 UTC, barmac commented
When I add more content, you need to scroll to see the third point:

![image](https://user-images.githubusercontent.com/28307541/150970569-d93d7b38-313c-4f1f-afe5-2ff879f4cc68.png)
![image](https://user-images.githubusercontent.com/28307541/150970581-fa7edb58-1eb6-4cf9-9513-0ccfab6c5a9c.png)

What do you think?

2022-01-25 12:55 UTC, MaxTru commented
I like the proposal provided by Maciej. LGTM.

2022-01-26 09:16 UTC, andreasgeier approved these changes

2022-01-26 09:24 UTC, MaxTru approved these changes

2022-01-26 13:55 UTC, merged