chore: rename to C7/C8 in deployment overlay
camunda/camunda-modeler pull request #2813
Opened 2022-03-17 08:26 UTC by smbea

Related to https://github.com/bpmn-io/internal-docs/issues/481

Artifacts:
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/rename-C7-C8-deployment/camunda-modeler-rename-C7-C8-deployment-linux-x64.tar.gz
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/rename-C7-C8-deployment/camunda-modeler-rename-C7-C8-deployment-mac.dmg
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/rename-C7-C8-deployment/camunda-modeler-rename-C7-C8-deployment-mac.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/rename-C7-C8-deployment/camunda-modeler-rename-C7-C8-deployment-win-ia32.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/rename-C7-C8-deployment/camunda-modeler-rename-C7-C8-deployment-win-x64.zip

Screenshot:
<img width="302" alt="Screenshot 2022-03-17 at 09 03 06" src="https://user-images.githubusercontent.com/25825387/158764023-a96cd6ab-9959-4eb3-b777-297d04b5160a.png">

2022-03-17 12:19 UTC, andreasgeier requested changes
When we change or add new labels, we should consider the [capitalization rule](https://github.com/camunda/camunda-modeler-design/blob/main/docs/technical-writing.md#capitalization)

Expected sentence case: `Deploy diagram`

Please note: `Camunda Platform 8 Self-Managed` is correct since it is a product name.

Not part of this issue, but feel free to fix the other labels in this dialog, too, if you think it is appropriate.

2022-03-17 12:33 UTC, smbea commented
@andreasgeier I changed the title and also the field labels since it was a quick change

2022-03-18 09:41 UTC, MaxTru approved these changes

2022-03-18 12:33 UTC, andreasgeier approved these changes
~~The artifact and screenshot is not updated but I'm going to approve based on @smbea's statement that it is fixed.~~

✅  Approved based on screenshot

2022-03-18 15:29 UTC, merged