chore(cloud deployment): set `SaaS` as default
camunda/camunda-modeler pull request #2858
Opened 2022-03-28 11:32 UTC by smbea

Closes #2832

2022-03-28 12:38 UTC, marstamm requested changes
With a clean user-dir, self-managed is selected by default:

![Recording 2022-03-28 at 14 36 04](https://user-images.githubusercontent.com/21984219/160399377-b87935d4-9242-4208-a8e7-26c6b1175b57.gif)

2022-03-28 14:55 UTC, MaxTru requested changes
* There is a strange bug surfaced by this change: the first click for me always brings up an error:
![bug](https://user-images.githubusercontent.com/42800119/160426104-cb2a4691-be5a-40e6-8685-63b077f50979.gif)
* Can we fix the CI errors?:
![Screenshot_20220328_165526](https://user-images.githubusercontent.com/42800119/160426251-c6a9d1d7-1091-4f91-acac-fcd662a87ff1.png)

2022-03-29 20:05 UTC, smbea commented
The error was because there was because there was an `autoFocus` there, triggering the field validation. I removed that since we also have `autoFocus` in the name field (which is the first one anyway).

2022-03-30 12:24 UTC, MaxTru approved these changes

2022-03-30 12:24 UTC, merged