feat(mixpanel): track overlays usage
camunda/camunda-modeler pull request #2987
Opened 2022-06-08 07:43 UTC by smbea

Related to #2934

2022-06-10 09:44 UTC, marstamm commented
Looks okay code-wise. Is there an easy way to test it?

2022-06-20 07:56 UTC, smbea commented
> Looks okay code-wise. Is there an easy way to test it?

To test see the results in Mixpanel, you need to request access to the app in IT. You can also just add a `debug` option in the code so that it logs all the events being fired. Other than that, you can use the flags MIXPANEL_TOKEN (please reach out via slack) and MIXPANEL_STAGE  (="int").

2022-06-21 08:05 UTC, MaxTru requested changes

2022-06-21 08:05 UTC, MaxTru commented on client/src/plugins/user-journey-statistics/event-handlers/__tests__/OverlayEventHandlerSpec.js
> +    describe('should send engine profile', () => {
Could we test here that this profile is actually sent (just as in the other tests)? E.g.,
```
      expect(track).to.have.been.calledWith('overlay:versionInfo:opened', {
        executionPlatform: 'Camunda Platform'
      });
```

Or is there any reason not to do that?

2022-06-22 09:27 UTC, MaxTru commented on client/src/plugins/user-journey-statistics/event-handlers/__tests__/OverlayEventHandlerSpec.js
> +    describe('should send engine profile', () => {
I saw it diffing from the other test cases. But you are right, for `executionPlatform` we always test using this pattern (also in existing other test cases).

2022-06-22 09:30 UTC, MaxTru approved these changes
Cool.

LGTM

2022-06-22 09:30 UTC, merged