deps: update modeling dependencies
camunda/camunda-modeler pull request #3150
Opened 2022-09-22 12:32 UTC by philippfromme

Related to https://github.com/camunda/camunda-modeler/issues/3083

2022-09-23 06:29 UTC, nikku commented
Does this close some other issues we [have marked as fixed upstream](https://tasks.bpmn.io/board?c=%21Done%2CBacklog%2CReady%2CIn+Progress%2CNeeds+Review)? If so, let's double check and mark accordingly in the commit.

2022-09-23 06:30 UTC, nikku requested changes
Please double check if other fixed upstream issues are closed by this.

2022-09-23 09:05 UTC, philippfromme commented
I included another fix (cf. https://github.com/camunda/linting/pull/19) and updated the commit message to close all related issues.

2022-09-26 07:47 UTC, nikku approved these changes

2022-09-26 18:40 UTC, merged