feat: 3444 Add MacOS specific switch tabs keyboard shortcuts
camunda/camunda-modeler pull request #3456
Opened 2023-02-10 07:47 UTC by codygulley

Closes #3444 

MacOS shortcuts for switching tabs next and previous is now `Cmd+SHIFT+[`  and `Cmd+SHIFT+]` respectively. Window shortcut remain `Control+TAB` and `Control+SHIFT+TAB` respectively.

2023-02-10 10:28 UTC, barmac requested changes
Hi, thanks for your contribution. 

If you want us to merge it, please follow the existing patterns for platform-specific code. This feature should be implemented in the [mac-menu-builder](https://github.com/camunda/camunda-modeler/blob/develop/app/lib/menu/mac-os/mac-menu-builder.js), so that the general code is platform-agnostic. 

Also, we want to keep the Ctrl+Tab / Ctrl+Shift+Tab shortcuts on MacOS too, as it's an established pattern to have dual shortcut, cf. how Google Chrome and Safari handle it. Check out https://stackoverflow.com/questions/57081237/electron-js-multiple-accelerators for a guidance how to implement it.

2023-02-10 18:01 UTC, codygulley commented
Thanks @barmac ! 

I implemented it where @nikku had pointed out 
> Seems like we need MacOS specific switching [here](https://github.com/camunda/camunda-modeler/blob/develop/app/lib/menu/menu-builder.js#L306).


Please confirm that my course of action is to undo these changes in `menu-builder.js` and implement them in `mac-menu-builder.js` ? 

If that is the correct, as I understand your comment:
> Also, we want to keep the Ctrl+Tab / Ctrl+Shift+Tab shortcuts on MacOS too, as it's an established pattern to have dual shortcut, cf. how Google Chrome and Safari handle it. Check out https://stackoverflow.com/questions/57081237/electron-js-multiple-accelerators for a guidance how to implement it.

 I should implement both sets of shortcuts in `mac-menu-builder.js` (?) or will the shortcuts in `menu-builder.js` be inherited and both sets of shortcuts will be available for use in MacOS?
 
 Thanks!
 - Cody

2023-02-10 19:38 UTC, nikku commented
I guess additional (visually hidden) shortcuts in mac-menu-builder would be sufficient.

2023-02-12 07:58 UTC, codygulley commented
I've updated the PR to have both the original shortcuts of `Ctrl+Tab` / `Ctrl+Shift+Tab` as well as including the `CommandOrControl+SHIFT+]` / `CommandOrControl+SHIFT+[` via hidden menu items, as @nikku  had suggested.

I was having problems trying to get the `mac-menu-builder.js` to override the switch tab functionality in `menu-builder.js` hopefully this will suffice.

2023-02-13 08:25 UTC, barmac commented
The `mac-menu-builder` works by overriding the Menu Builder methods. No magic here. Read more on inheritance at https://www.w3schools.com/js/js_class_inheritance.asp

I added the required implementation and will squash this PR after CI run.

2023-02-13 08:37 UTC, merged